"use strict";
var Icon;
(function (Icon) {
    Icon[Icon["osobni_seda_stojici.png"] = 111] = "osobni_seda_stojici.png";
    Icon[Icon["osobni_seda.png"] = 112] = "osobni_seda.png";
    Icon[Icon["osobni_modra_stojici.png"] = 121] = "osobni_modra_stojici.png";
    Icon[Icon["osobni_modra.png"] = 122] = "osobni_modra.png";
    Icon[Icon["osobni_zelena_stojici.png"] = 131] = "osobni_zelena_stojici.png";
    Icon[Icon["osobni_zelena.png"] = 132] = "osobni_zelena.png";
    Icon[Icon["osobni_zluta_stojici.png"] = 141] = "osobni_zluta_stojici.png";
    Icon[Icon["osobni_zluta.png"] = 142] = "osobni_zluta.png";
    Icon[Icon["osobni_oranzova_stojici.png"] = 151] = "osobni_oranzova_stojici.png";
    Icon[Icon["osobni_oranzova.png"] = 152] = "osobni_oranzova.png";
    Icon[Icon["osobni_cervena_stojici.png"] = 161] = "osobni_cervena_stojici.png";
    Icon[Icon["osobni_cervena.png"] = 162] = "osobni_cervena.png";
    Icon[Icon["osobni_hneda_stojici.png"] = 171] = "osobni_hneda_stojici.png";
    Icon[Icon["osobni_hneda.png"] = 172] = "osobni_hneda.png";
    Icon[Icon["nakladni_seda_stojici.png"] = 211] = "nakladni_seda_stojici.png";
    Icon[Icon["nakladni_seda.png"] = 212] = "nakladni_seda.png";
    Icon[Icon["nakladni_modra_stojici.png"] = 221] = "nakladni_modra_stojici.png";
    Icon[Icon["nakladni_modra.png"] = 222] = "nakladni_modra.png";
    Icon[Icon["nakladni_zelena_stojici.png"] = 231] = "nakladni_zelena_stojici.png";
    Icon[Icon["nakladni_zelena.png"] = 232] = "nakladni_zelena.png";
    Icon[Icon["nakladni_zluta_stojici.png"] = 241] = "nakladni_zluta_stojici.png";
    Icon[Icon["nakladni_zluta.png"] = 242] = "nakladni_zluta.png";
    Icon[Icon["nakladni_oranzova_stojici.png"] = 251] = "nakladni_oranzova_stojici.png";
    Icon[Icon["nakladni_oranzova.png"] = 252] = "nakladni_oranzova.png";
    Icon[Icon["nakladni_cervena_stojici.png"] = 261] = "nakladni_cervena_stojici.png";
    Icon[Icon["nakladni_cervena.png"] = 262] = "nakladni_cervena.png";
    Icon[Icon["nakladni_hneda_stojici.png"] = 271] = "nakladni_hneda_stojici.png";
    Icon[Icon["nakladni_hneda.png"] = 272] = "nakladni_hneda.png";
})(Icon = exports.Icon || (exports.Icon = {}));
;
//# sourceMappingURL=responses.js.map